=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Cards.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xsd:element name="CardTypes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Cards">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Card">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element minOccurs="0" name="upgradeData">
                      <xsd:complexType>
                        <xsd:attribute name="RechargeMult" type="xsd:decimal" use="required" />
						            <xsd:attribute name="RechargeMod" type="xsd:decimal" use="required" />
						            <xsd:attribute name="RangeMult" type="xsd:decimal" use="required" />
                        <xsd:attribute name="RangeMod" type="xsd:decimal" use="required" />
						            <xsd:attribute name="DamageMult" type="xsd:decimal" use="required" />
                        <xsd:attribute name="DamageMod" type="xsd:decimal" use="required" />
                        <xsd:attribute name="WaveBonus" type="xsd:unsignedByte" use="required" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="towerData">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="towerColor" minOccurs="0">
                            <xsd:complexType>
                              <xsd:attribute name="r" type="xsd:string" use="required" />
                              <xsd:attribute name="g" type="xsd:string" use="required" />
                              <xsd:attribute name="b" type="xsd:string" use="required" />
                              <xsd:attribute name="a" type="xsd:string" use="required" />
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="Recharge" type="xsd:decimal" use="required" />
                        <xsd:attribute name="Range" type="xsd:decimal" use="required" />
                        <xsd:attribute name="Damage" type="xsd:decimal" use="required" />
                        <xsd:attribute name="Lifespan" type="xsd:unsignedByte" use="required" />
                        <xsd:attribute name="UpgradeCap" type="xsd:unsignedByte" use="required" />
                        <xsd:attribute name="Sprite" type="xsd:string" use="required" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="effectData">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="Effects">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element maxOccurs="unbounded" name="Effect" type="tEffect" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="Type" type="xsd:string" use="required" />
                  <xsd:attribute name="Name" type="xsd:string" use="required" />
                  <xsd:attribute name="Description" type="xsd:string" use="optional" />
                  <xsd:attribute name="Charges" type="xsd:unsignedByte" use="required" />
                  <xsd:attribute name="Art" type="xsd:string" use="required" />
                  <xsd:attribute name="Tooltip" type="xsd:string" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="cardFileDependencies" type="xsd:string" use="optional" />
      <xsd:attribute name="enemyFileDependencies" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="tEffect">
    <xsd:sequence>
      <xsd:element name="Effect" type="tEffect" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="strength" type="xsd:decimal" use="optional" />
    <xsd:attribute name="argument" type="xsd:string" use="optional" />
  </xsd:complexType>
  
</xs:schema>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Documentation/Example Card Dependencies.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This is a fully functioning mod file.  Copy it to StreamingAssets/XML/Modded Cards to see it in action! -->
<!-- This is an example of a simple mod file that depends on four others: the card files Example Cards.xml and Example Card Dependency.xml and the enemy files Example Enemies.xml and Example Enemies Dependency.xml.-->
<!-- Note cardFileDependencies and enemyFileDependencies attributes on the next line.-->
<CardTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Cards.xsd" cardFileDependencies="Example Cards, Example Card Dependency, Dev Cards" enemyFileDependencies="Example Enemies, Example Enemy Dependency">
  <Cards>
    <Card Name="Free Mana Tap" Type="spell" Description="Draw five cards.  Does not consume a charge, but still costs points because you're a jerk for using this" Charges="3" Art="Summon_Tower_Basic.png" Tooltip="Tower_Basic.png">
      <effectData>
        <Effects>
		      <Effect name="addCharges" strength="1" />
          <Effect name="drawCard" strength="5" />
          <Effect name="score" strength="-500" />
        </Effects>
      </effectData>
    </Card>
  </Cards>
</CardTypes>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Documentation/Example Cards.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This is a fully functioning mod file.  Copy it to StreamingAssets/XML/Modded Cards to see it in action! -->
<CardTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Cards.xsd">
  <!-- 	Cards listed here will not appear in game unless they are listed in a deck!
		string Type: must be one of "tower", "upgrade", or "spell".  Each one uses different attributes (see below)
		string Name: name of the card.  if a card of this name already exists, the existing card will be OVERWRITTEN.
		string Description: describes what the card does
		byte   Charges: number of times this card can be used before being destroyed
		string Art: filename of the image to be placed on the card.  Do NOT include the extension.  The art must be a .png and placed in StreamingAssets/Art/Card Art.  A default is used if the image cant be found or this property is missing.
		string Tooltip: filename of the image to be placed on the cursor when casting.  Do NOT include the extension.  The tooltip must be a .png and placed in StreamingAssets/Art/Sprites.  A default is used if the image cant be found or this property is missing.
    bool   Token: whether or not this is a token.  Tokens can be spawned by effects but cannot be included in a deck.-->
  <Cards>
	<!-- because a card with this name already exists in the base game, that version will be overwritten.  This modified version is more powerful, but gets fewer charges -->
    <Card Name="Basic Tower" Type="tower" Description="Example mod: Summons a basic tower" Charges="3" Art="Summon_Tower_Basic.png" Tooltip="Tower_Basic.png" Token="false">
	<!--	Tower specific properties:
			float Recharge: time, in seconds, the tower must wait between shots
			float Range: distance the tower can fire
			float Damage: amount of damage dealt
			byte  Lifespan: number of waves the tower remains on the map.  can be extended with upgrades or spells
      byte  UpgradeCap: number of times the tower can be upgraded.
			string Sprite: filename of the image to represent the tower in the world.  Do NOT include the extension.  The image must be a .png and placed in StreamingAssets/Art/Sprites.  A default is used if the image cant be found or this property is missing.-->
      <towerData Recharge="1.5" Range="3.5" Damage="25" Lifespan="5" UpgradeCap="5" Sprite="Tower_Basic.png" />
    </Card>
	<!-- because this is a new card, it will not appear in game unless listed in a deck (such as in the example level file in this same folder) -->
    <Card Name="Example Upgrade" Type="upgrade" Description="+1 to all properties.  +10% to all properties." Charges="2" Art="Summon_Tower_Basic.png" Tooltip="Tower_Basic.png" Token="false">
	<!--	upgrade specific properties:
			float RechargeMult: multiplier for tower recharge.  Use 1.0 for no effect.
			float DamageMult: multiplier for tower damage.  Use 1.0 for no effect.
			float RangeMult: multiplier for tower range.  Use 1.0 for no effect.
			float RechargeMod: added to tower recharge.  Use 0.0 for no effect.
			float DamageMod: added to tower damage.  Use 0.0 for no effect.
			float rangeMod: added to tower range.  Use 0.0 for no effect.
			byte  waveBonus: number of waves added to the tower's remaining lifespan.  Use 0 for no effect-->
      <upgradeData RechargeMult="1.1" RangeMult="1.1" DamageMult="1.1" RechargeMod="2" RangeMod="1" DamageMod="1" WaveBonus="1" />
    </Card>
    <Card Name="Free Life Tap" Type="spell" Description="Draw five cards.  Does not consume a charge." Charges="3" Art="Summon_Tower_Basic.png" Tooltip="Tower_Basic.png" Token="false">
      <!--to add effects, you provide a list of effects applied by the card.  
      You can add them to any type of card, but most only make sense on specific kinds of cards, and some dont make sense on cards at all
      For a complete list, see "available effects.txt"
      The listed effects also determine how the card must be cast.
      For example, if a spell affects a tower, the player will have to select a tower in order to play the card.
			The list of effects is hard coded, but you can combine them in whatever way you wish.  Effects are applied in the order listed.-->
      <effectData>
        <Effects>
	    <!--string name: name of the effect (see below)
			float  strength: strength of the effect.  If the effect doesn't use this, you can leave it out.
			string argument: extra data for the effect.  If the effect doesn't use this, you can leave it out. -->
		  <Effect name="addCharges" strength="1" />
          <Effect name="drawCard" strength="5" />
        </Effects>
      </effectData>
    </Card>
  </Cards>
</CardTypes>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Documentation/Example Card Dependency.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This is a fully functioning mod file.  Copy it to StreamingAssets/XML/Modded Cards to see it in action! -->
<!-- This is an example of a simple mod file that depends on two others: the card file Example Cards.xml and the enemy file Example Enemies.xml.-->
<!-- Note cardFileDependencies and enemyFileDependencies attributes on the next line.-->
<CardTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Cards.xsd" cardFileDependencies="Example Cards" enemyFileDependencies="Example Enemies">
  <Cards>
    <Card Name="Free Life Tap" Type="spell" Description="Draw five cards.  Does not consume a charge, but still costs points because you're a jerk for using this" Charges="3" Art="Summon_Tower_Basic.png" Tooltip="Tower_Basic.png" Token="false">
      <effectData>
        <Effects>
		      <Effect name="addCharges" strength="1" />
          <Effect name="drawCard" strength="5" />
          <Effect name="score" strength="-500" />
        </Effects>
      </effectData>
    </Card>
  </Cards>
</CardTypes>
