=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Decks.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xsd:element name="PlayerDecks">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Decks">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Deck">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Cards">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element maxOccurs="unbounded" name="Card">
                            <xsd:complexType>
                              <xsd:attribute name="name" type="xsd:string" use="required" />
                              <xsd:attribute name="count" type="xsd:unsignedByte" use="required" />
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="name" type="xsd:string" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xs:schema>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Decks.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayerDecks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="Decks.xsd">
  <Decks>
    <Deck name="Patient Power">
      <Cards>
        <Card name="Heavy Tower" count="10" />
        <Card name="Basic Upgrade" count="20" />
      </Cards>
    </Deck>
    <Deck name="Prototype Deck">
      <Cards>
        <Card name="Fast Tower" count="2" />
        <Card name="Heavy Tower" count="3" />
        <Card name="Basic Upgrade" count="5" />
        <Card name="Enrage" count="2" />
        <Card name="Basic Tower" count="5" />
        <Card name="Heavy Upgrade" count="2" />
        <Card name="Mana Tap" count="1" />
        <Card name="Shield" count="1" />
        <Card name="Reinforce" count="1" />
        <Card name="Recycle" count="1" />
        <Card name="Summon Swarm" count="1" />
        <Card name="Time Crunch" count="1" />
      </Cards>
    </Deck>
  </Decks>
</PlayerDecks>

=== mctribble/Card-Defense/Assets/StreamingAssets/Save/PlayerDecks.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayerDecks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../XML/Decks.xsd">
  <Decks>
    <Deck name="Spleen Power">
      <Cards>
        <Card name="Heavy Tower" count="10" />
        <Card name="Spitfire Upgrade" count="10" />
        <Card name="Fast Upgrade" count="10"/>
        <Card name="Shield" count="10"/>
      </Cards>
    </Deck>
  </Decks>
</PlayerDecks>
