=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Enemies.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xsd:element name="EnemyTypes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Enemies">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Enemy">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="rankInfo">
                      <xsd:complexType>
                        <xsd:attribute name="rankUpSpawnCount" type="xsd:int"   use="required" />
                        <xsd:attribute name="spawnCostMult"    type="xsd:int"   use="required" />
                        <xsd:attribute name="attackMult"       type="xsd:float" use="required" />
                        <xsd:attribute name="maxHealthMult"    type="xsd:float" use="required" />
                        <xsd:attribute name="unitSpeedMult"    type="xsd:float" use="required" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="unitColor">
                      <xsd:complexType>
                        <xsd:attribute name="r" type="xsd:float" use="required" />
                        <xsd:attribute name="g" type="xsd:float" use="required" />
                        <xsd:attribute name="b" type="xsd:float" use="required" />
                        <xsd:attribute name="a" type="xsd:float" use="required" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="effectData">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="Effects">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element maxOccurs="unbounded" name="Effect" type="tEffect" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="name"      type="xsd:string"        use="required" />
                  <xsd:attribute name="spawnCost" type="xsd:unsignedShort" use="required" />
                  <xsd:attribute name="attack"    type="xsd:unsignedByte"  use="required" />
                  <xsd:attribute name="maxHealth" type="xsd:unsignedShort" use="required" />
                  <xsd:attribute name="unitSpeed" type="xsd:float"         use="required" />
                  <xsd:attribute name="sprite"    type="xsd:string"        use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="enemyFileDependencies" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="tEffect">
    <xsd:sequence>
      <xsd:element name="Effect" type="tEffect" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" use="required" >
      <xsd:simpleType>
        <xsd:restriction base="xsd:string">
          <xsd:enumeration value="addCharges" />
          <xsd:enumeration value="allTowersLifespanBonus" />
          <xsd:enumeration value="armor" />
          <xsd:enumeration value="armorPierce" />
          <xsd:enumeration value="attackColor" />
          <xsd:enumeration value="budgetPercentageChange" />
          <xsd:enumeration value="cannotBeDiscarded" />
          <xsd:enumeration value="chainHit" />
          <xsd:enumeration value="changeWaveType" />
          <xsd:enumeration value="conjureCard" />
          <xsd:enumeration value="conjureEnemyCard" />
          <xsd:enumeration value="conjureSpecificCard" />
          <xsd:enumeration value="conjureSpellCard" />
          <xsd:enumeration value="conjureTowerCard" />
          <xsd:enumeration value="conjureUpgradeCard" />
          <xsd:enumeration value="customDescription" />
          <xsd:enumeration value="damageHand" />
          <xsd:enumeration value="damagePercent" />
          <xsd:enumeration value="damagePlayer" />
          <xsd:enumeration value="dieRoll" />
          <xsd:enumeration value="discardChosenCard" />
          <xsd:enumeration value="discardRandomCard" />
          <xsd:enumeration value="drawCard" />
          <xsd:enumeration value="drawEnemyCard" />
          <xsd:enumeration value="drawSpellCard" />
          <xsd:enumeration value="drawTowerCard" />
          <xsd:enumeration value="drawUpgradeCard" />
          <xsd:enumeration value="effectCharges" />
          <xsd:enumeration value="effectCooldown" />
          <xsd:enumeration value="everyRound" />
          <xsd:enumeration value="ifRollRange" />
          <xsd:enumeration value="infiniteTowerLifespan" />
          <xsd:enumeration value="invScaleAttackWithDamage" />
          <xsd:enumeration value="invScaleEffectWithDamage" />
          <xsd:enumeration value="invScaleEffectWithTime" />
          <xsd:enumeration value="invScaleSpedWithTime" />
          <xsd:enumeration value="invScaleSpeedWithDamage" />
          <xsd:enumeration value="limitedAmmo" />
          <xsd:enumeration value="manualFire" />
          <xsd:enumeration value="maxOvercharge" />
          <xsd:enumeration value="noUpgradeCost" />
          <xsd:enumeration value="onAttack" />
          <xsd:enumeration value="onCardDrawn" />
          <xsd:enumeration value="onSpawned" />
          <xsd:enumeration value="overchargeDamage" />
          <xsd:enumeration value="percentageChance" />
          <xsd:enumeration value="poison" />
          <xsd:enumeration value="redrawTowerOnDeath" />
          <xsd:enumeration value="reduceEnemyEffectOnDamage" />
          <xsd:enumeration value="reloadAmmo" />
          <xsd:enumeration value="regeneration" />
          <xsd:enumeration value="replaceRandomCard" />
          <xsd:enumeration value="replaceRandomCardWithSpell" />
          <xsd:enumeration value="replaceRandomCardWithTower" />
          <xsd:enumeration value="replaceRandomCardWithUpgrade" />
          <xsd:enumeration value="ResonantTowerAttackMod" />
          <xsd:enumeration value="ResonantTowerAttackMult" />
          <xsd:enumeration value="ResonantTowerRangeMod" />
          <xsd:enumeration value="returnsToTopOfDeck" />
          <xsd:enumeration value="setRange" />
          <xsd:enumeration value="scaleAttackWithDamage" />
          <xsd:enumeration value="scaleEffectByTowerAttack" />
          <xsd:enumeration value="scaleEffectWithDamage" />
          <xsd:enumeration value="scaleEffectWithRank" />
          <xsd:enumeration value="scaleEffectWithTime" />
          <xsd:enumeration value="scaleSpeedWithDamage" />
          <xsd:enumeration value="scaleSpeedWithTime" />
          <xsd:enumeration value="score" />
          <xsd:enumeration value="secondaryBurst" />
          <xsd:enumeration value="shuffle" />
          <xsd:enumeration value="slowTarget" />
          <xsd:enumeration value="spawnEnemyOnDeath" />
          <xsd:enumeration value="splashDamage" />
          <xsd:enumeration value="statPercentChangePerRound" />
          <xsd:enumeration value="targetAll" />
          <xsd:enumeration value="targetArmor" />
          <xsd:enumeration value="targetBurst" />
          <xsd:enumeration value="targetClosest" />
          <xsd:enumeration value="targetHealth" />
          <xsd:enumeration value="targetLowHealth" />
          <xsd:enumeration value="targetMouse" />
          <xsd:enumeration value="targetMultishot" />
          <xsd:enumeration value="targetOrthogonal" />
          <xsd:enumeration value="targetRandom" />
          <xsd:enumeration value="targetSpeed" />
          <xsd:enumeration value="timePercentageChange" />
          <xsd:enumeration value="upgradeAllTowers" />
          <xsd:enumeration value="upgradesForbidden" />
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
    <xsd:attribute name="strength" type="xsd:decimal" use="optional" />
    <xsd:attribute name="argument" type="xsd:string" use="optional" />
  </xsd:complexType>
  
</xs:schema>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Documentation/Example Enemy Dependency.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This is a fully functioning mod file.  Copy it to StreamingAssets/XML/Modded Enemies to see it in action! -->
<!--	This time, we want to create a file that depends on Example Enemies.Xml.  We will add ExEnemy2 and override ExEnemy. Note the new enemyFileDepencies attribute on the next line -->
<EnemyTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Enemies.xsd" enemyFileDependencies="Example Enemies">
  <Enemies>
    <Enemy name="ExEnemy" spawnCost="1" attack="1" maxHealth="1" unitSpeed="2" sprite="Enemy_Basic.png">
      <rankInfo rankUpSpawnCount="200" spawnCostMult="2" attackMult="2" maxHealthMult="2" unitSpeedMult="1" />
      <unitColor r="0.1" g="0.1" b="0.1" a="0.8" />
    </Enemy>
    <Enemy name="ExEnemy2" spawnCost="1000" attack="50" maxHealth="9999" unitSpeed="1" sprite="Enemy_Basic.png">
      <rankInfo rankUpSpawnCount="200" spawnCostMult="2" attackMult="2" maxHealthMult="2" unitSpeedMult="1" />
      <unitColor r="1" g="1" b="1" a="1"/>
    </Enemy>
  </Enemies>
</EnemyTypes>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Documentation/Example Enemies.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This is a fully functioning mod file.  Copy it to StreamingAssets/XML/Modded Enemies to see it in action! -->
<EnemyTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Enemies.xsd">
  <!--	Enemies added here can spawn in random waves, or be specified in a level's wave list. -->
    
    <Enemies>
      <!-- enemy attributes are as follows:
      string name:      The name of the enemy.  If an enemy of this name already exists, the existing enemy is OVERWRITTEN!
      byte   spawnCost: the wave spawner must "pay" this much to spawn an enemy of this type.
      short  maxHealth: the amount of damage this unit can take before dying.
      byte   damage:    the amount of charges removed from the player's deck when this enemy reaches their goal
      byte   unitSpeed: how fast this unit moves-->
      <!--because an enemy named Tank already exists in the base game, that version will be overwritten. This variation of tank has very low health. -->
      <Enemy name="Tank" spawnCost="100" attack="10" maxHealth="8" unitSpeed="1" sprite="Enemy_Basic.png">
        <!-- rankInfo defines how, and when, enemy waves will rank up:
        string rankUpSpawnCount: if the wave would spawn more enemies than this, it ranks up
        float  spawnCostMult:    spawnCost is multiplied by this much every time the wave ranks up.  (in this case, spawn cost will be 2x normal at rank II, 4x normal at rank III, etc.)
        float  attackMult:       attack    is multiplied by this much every time the wave ranks up.
        float  maxHealthMult:    maxHealth is multiplied by this much every time the wave ranks up.
        float  unitSpeedMult:    unitSpeed is multiplied by this much every time the wave ranks up.  Note that base game enemies do not actually use this, and there is a global speed limit in place to prevent enemies outrunning bullets.-->
        <rankInfo rankUpSpawnCount="200" spawnCostMult="2" attackMult="2" maxHealthMult="2" unitSpeedMult="1" />
        <!--unitColor: the enemy sprite is colorized with this.  Values range from 0 to 1.-->
        <unitColor r="0" g="0" b="1" a="1" />
    </Enemy>
	<!--because an enemy of this name does not exist in base game, this will be added to the list.
		It will only appear in levels that spawn at least some waves at random, or include it in their explicit wave list (such as the example level file in this folder)
		these enemies are very slow and always die in one hit, but spawn in great numbers-->
    <Enemy name="ExEnemy" spawnCost="1" attack="1" maxHealth="1" unitSpeed="1" sprite="Enemy_Basic.png">
      <rankInfo rankUpSpawnCount="200" spawnCostMult="2" attackMult="2" maxHealthMult="2" unitSpeedMult="1" />
      <unitColor r="0" g="0" b="0" a="1" />
    </Enemy>
  </Enemies>
</EnemyTypes>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Enemies.xml
<?xml version="1.0" encoding="utf-8"?>
<EnemyTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="Enemies.xsd">
  <Enemies>
    <Enemy name="Standard" spawnCost="20" damage="2" maxHealth="40" unitSpeed="2" sprite="Enemy_Basic">
      <unitColor r="0" g="1" b="0" a="1" />
    </Enemy>
    <Enemy name="Swarm" spawnCost="5" damage="1" maxHealth="4" unitSpeed="5" sprite="Enemy_Basic">
      <unitColor r="1" g="0" b="0" a="1" />
    </Enemy>
    <Enemy name="Tank" spawnCost="100" damage="5" maxHealth="450" unitSpeed="1" sprite="Enemy_Basic">
      <unitColor r="0" g="0" b="1" a="1" />
      <effectData>
        <Effects>
          <Effect name="armor" strength="20" />
        </Effects>
      </effectData>
    </Enemy>
  </Enemies>
</EnemyTypes>
