=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Level.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xsd:element name="Level">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="difficulty" type="xsd:string" />
        <xsd:element name="description" type="xsd:string" />
        <xsd:element name="randomWaveCount" type="xsd:unsignedByte" />
        <xsd:element name="waveGrowthAbsolute" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthLinear" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthSquared" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthExponential" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveTimeLinear" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveTimeMax" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="disableGatherPower" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="Waves">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" minOccurs="0" name ="Wave">
                <xsd:complexType>
                  <xsd:attribute name="type" type="xsd:string" use="required" />
                  <xsd:attribute name="budget" type="xsd:int" use="required" />
                  <xsd:attribute name="time" type="xsd:float" use="required" />
                  <xsd:attribute name="message" type="xsd:string" use="optional" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Spawners">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Spawner">
                <xsd:complexType>
                  <xsd:attribute name="spawnX" type="xsd:float" use="required" />
                  <xsd:attribute name="spawnY" type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="PathSegments">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Segment">
                <xsd:complexType>
                  <xsd:attribute name="startX" type="xsd:float" use="required" />
                  <xsd:attribute name="startY" type="xsd:float" use="required" />
                  <xsd:attribute name="endX"   type="xsd:float" use="required" />
                  <xsd:attribute name="endY"   type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Towers">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Tower" maxOccurs="unbounded" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Upgrades" maxOccurs="unbounded" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="Upgrade" maxOccurs="unbounded" minOccurs="0">
                            <xsd:complexType>
                              <xsd:attribute name="Name" type="xsd:string" use="required" />
                              <xsd:attribute name="Count" type="xsd:unsignedByte" use="required" />
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="name" type="xsd:string" use="required" />
                  <xsd:attribute name="x" type="xsd:float" use="required" />
                  <xsd:attribute name="y" type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="shuffleDeck" type="xsd:boolean"/>
        <xsd:choice>
          <xsd:element name="levelDeck">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="Cards">
                  <xsd:complexType>
                    <xsd:sequence>
                      <xsd:element maxOccurs="unbounded" name="Card">
                        <xsd:complexType>
                          <xsd:attribute name="name" type="xsd:string" use="required" />
                          <xsd:attribute name="count" type="xsd:unsignedByte" use="required" />
                        </xsd:complexType>
                      </xsd:element>
                    </xsd:sequence>
                  </xsd:complexType>
                </xsd:element>
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="premadeDeckName" type="xsd:string" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="background" type="xsd:string" />
      <xsd:attribute name="backgroundTileRate" type="xsd:float" />
      <xsd:attribute name="centerBackground" type="xsd:boolean" use="optional" />
      <xsd:attribute name="cardFileDependencies" type="xsd:string" use="optional" />
      <xsd:attribute name="enemyFileDependencies" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
</xs:schema>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/strategy tutorial.xml
<?xml version="1.0" encoding="utf-8"?>
<!--This is only a template to build new levels from.  It works as a playable level, but isnt terribly interesting.-->
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Grass.png">
  <!-- 	This many waves will be generated randomly and added to the END of the wave list -->
  <randomWaveCount>0</randomWaveCount>
  <!-- 	These waves will be gauranteed to spawn, in order.
		type: name of the enemy type to spawn
		budget: how much the wave spawner can "spend" on spawning enemies
		time: how many seconds the enemies spawn for.  Shorter time spans result in more densely packed groups.
		message: optional message that appears at the start of the wave-->
  <Waves>
    <Wave type="Swarm"    budget ="1500" time="15" message="Lets look at some slightly more advanced strategy.  In this example, your defenses are already strong enough to defeat the enemy.  However, your hand consists of nothing but Basic Towers and Heavy upgrades.  You should play at least one of these so you can draw something more useful for the next wave.  Be careful, though!  Heavy upgrades slow down towers in exchange for doubling their damage.  DO NOT play these on your fast towers: they will actually become weaker since the speed penalty will outweigh the damage buff." />
    <Wave type="Tank"     budget ="1500" time="15" message="Oh no!  This next wave will be Tank monsters, which your fast towers are ill-equipped to handle.  If you followed our advice in the last round, you should draw a Summon Swarm card.  This card will harm you, but not nearly as much as the incoming tanks will.  Play Summon Swarm to turn the incoming wave into Swarm monsters so you can survive" />
    <Wave type="Standard" budget ="1500" time="15" message="You should be able to handle this wave fine, but you have another problem: your towers have only one wave left on them, but there are two more waves to fend off.  You can always build more towers, but there is a better way: play reinforce so that you can keep the ones you have a little longer.  Not only is this cheaper, but it allows you to retain any upgrades your towers may already have.  " />
    <Wave type="Standard" budget ="2000" time="15" message="This wave is tough, but not insurmountable.  Feel free to play your entire hand: there are no more waves after this, and returning the cards you are holding to the deck will help protect you in case some of the enemies break through your defenses." />
  </Waves>
  <!--	positions at which the enemies can spawn -->
  <Spawners>
    <Spawner spawnX="-1"  spawnY="15" />
    <Spawner spawnX="0"   spawnY="15" />
    <Spawner spawnX="1"   spawnY="15" />
    <Spawner spawnX="-1"  spawnY="-15" />
    <Spawner spawnX="0"   spawnY="-15" />
    <Spawner spawnX="1"   spawnY="-15" />
    <Spawner spawnX="15"  spawnY="-1" />
    <Spawner spawnX="15"  spawnY="0" />
    <Spawner spawnX="15"  spawnY="1" />
    <Spawner spawnX="-15" spawnY="-1" />
    <Spawner spawnX="-15" spawnY="0" />
    <Spawner spawnX="-15" spawnY="1" />
  </Spawners>
  <!--	positions at which each path segment starts and ends.  Make sure each spawner has a segment which starts at the same position.
		note that the pathfinder is very basic at the moment: it will only search for other segments further down the list that start at
		the same position their last segment ended at, and it will take the first option it finds.
		This means you must list the segments in order, and the path can combine but not really branch off because all enemies will take the same path.-->
  <PathSegments>
    <Segment startX="-1"  startY="15"  endX="-1" endY="1" />
    <Segment startX="0"   startY="15"  endX="0"  endY="1" />
    <Segment startX="1"   startY="15"  endX="1"  endY="1" />
    <Segment startX="-1"  startY="-15" endX="-1" endY="-1" />
    <Segment startX="0"   startY="-15" endX="0"  endY="-1" />
    <Segment startX="1"   startY="-15" endX="1"  endY="-1" />
    <Segment startX="15"  startY="-1"  endX="1"  endY="-1" />
    <Segment startX="15"  startY="0"   endX="1"  endY="0" />
    <Segment startX="15"  startY="1"   endX="1"  endY="1" />
    <Segment startX="-15" startY="-1"  endX="-1" endY="-1" />
    <Segment startX="-15" startY="0"   endX="-1" endY="0" />
    <Segment startX="-15" startY="1"   endX="-1" endY="1" />
    <Segment startX="-1"  startY="1"   endX="0"  endY="0" />
    <Segment startX="0"   startY="1"   endX="0"  endY="0" />
    <Segment startX="1"   startY="1"   endX="0"  endY="0" />
    <Segment startX="-1"  startY="-1"  endX="0"  endY="0" />
    <Segment startX="0"   startY="-1"  endX="0"  endY="0" />
    <Segment startX="1"   startY="-1"  endX="0"  endY="0" />
    <Segment startX="-1"  startY="0"   endX="0"  endY="0" />
    <Segment startX="1"   startY="0"   endX="0"  endY="0" />
  </PathSegments>
  <!--	this section is for starting the level with towers already on the field.  See Example Level.xml for details-->
  <Towers>
	<Tower name="Fast Tower" x="-0.5" y="-1.5" />
    <Tower name="Fast Tower" x="0.5"  y="-1.5" />
  	<Tower name="Fast Tower" x="-0.5" y="1.5" />
    <Tower name="Fast Tower" x="0.5"  y="1.5" />
    <Tower name="Fast Tower" x="-1.5" y="-0.5" />
    <Tower name="Fast Tower" x="1.5"  y="-0.5" />
    <Tower name="Fast Tower" x="-1.5" y="0.5" />
    <Tower name="Fast Tower" x="1.5"  y="0.5" />
    <Tower name="Fast Tower" x="1.5"  y="1.5" />
    <Tower name="Fast Tower" x="-1.5" y="1.5" />
    <Tower name="Fast Tower" x="1.5"  y="-1.5" />
    <Tower name="Fast Tower" x="-1.5" y="-1.5" />
  </Towers>
  <!--  this determines whether or not the deck is shuffled at game start.  If false, cards appear in the order listed below-->
  <shuffleDeck>false</shuffleDeck>
  <!--	this is the deck the player is given to use in this level by default.  the deck name is currently unused.-->
  <levelDeck name="template">
    <!-- name: name of the card
		 count: how many of that card are present-->
    <Cards>
      <Card name="Basic Tower"    count="5" />
      <Card name="Heavy Upgrade"  count="5" />
      <Card name="Summon Swarm"   count="1" />
      <Card name="Heavy Upgrade"  count="1" />
      <Card name="Reinforce"      count="1" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Prototype.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>medium</difficulty>
  <description>First level added to the game</description>
  <randomWaveCount>25</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="15" spawnY="0" />
  </Spawners>
  <PathSegments>
    <Segment startX="15" startY="0" endX="10" endY="0" />
    <Segment startX="10" startY="0" endX="10" endY="1" />
    <Segment startX="10" startY="0" endX="10" endY="-1" />
    <Segment startX="10" startY="1" endX="6" endY="1" />
    <Segment startX="6" startY="1" endX="6" endY="0" />
    <Segment startX="10" startY="-1" endX="6" endY="-1" />
    <Segment startX="6" startY="-1" endX="6" endY="0" />
    <Segment startX="10" startY="0" endX="6" endY="0" />
    <Segment startX="6" startY="0" endX="4" endY="0" />
    <Segment startX="4" startY="0" endX="4" endY="4" />
    <Segment startX="4" startY="4" endX="-4" endY="4" />
    <Segment startX="-4" startY="4" endX="-4" endY="-2" />
    <Segment startX="-4" startY="-2" endX="0" endY="-2" />
    <Segment startX="0" startY="-2" endX="0" endY="2" />
    <Segment startX="0" startY="2" endX="-2" endY="2" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Starter Deck</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Parallel tasks 2.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>hard</difficulty>
  <description>A challenging map with nine paths to defend</description>
  <randomWaveCount>15</randomWaveCount>
  <waveGrowthAbsolute>30</waveGrowthAbsolute>
  <waveGrowthLinear>6</waveGrowthLinear>
  <waveGrowthSquared>2</waveGrowthSquared>
  <waveGrowthExponential>1</waveGrowthExponential>
  <waveTimeLinear>1</waveTimeLinear>
  <Waves />
  <Spawners>
    <Spawner spawnX="-5" spawnY="-5" />
    <Spawner spawnX="-3" spawnY="-5" />
    <Spawner spawnX="-1" spawnY="-5" />
    <Spawner spawnX="1" spawnY="-5" />
    <Spawner spawnX="3" spawnY="-5" />
    <Spawner spawnX="-5" spawnY="-3" />
    <Spawner spawnX="-5" spawnY="-1" />
    <Spawner spawnX="-5" spawnY="1" />
    <Spawner spawnX="-5" spawnY="3" />
  </Spawners>
  <PathSegments>
    <Segment startX="-5" startY="-5" endX="5" endY="5" />
    <Segment startX="-3" startY="-5" endX="5" endY="3" />
    <Segment startX="-1" startY="-5" endX="5" endY="1" />
    <Segment startX="1" startY="-5" endX="5" endY="-1" />
    <Segment startX="3" startY="-5" endX="5" endY="-3" />
    <Segment startX="-5" startY="-3" endX="3" endY="5" />
    <Segment startX="-5" startY="-1" endX="1" endY="5" />
    <Segment startX="-5" startY="1" endX="-1" endY="5" />
    <Segment startX="-5" startY="3" endX="-3" endY="5" />
  </PathSegments>
  <Towers>
    <Tower name="Fast Tower" x="5" y="-5">
      <Upgrades>
        <Upgrade Name="Fast Upgrade" Count="3" />
      </Upgrades>
    </Tower>
    <Tower name="Fast Tower" x="-5" y="5">
      <Upgrades>
        <Upgrade Name="Fast Upgrade" Count="3" />
      </Upgrades>
    </Tower>
  </Towers>
  <shuffleDeck>true</shuffleDeck>
  <levelDeck name="New Deck">
    <Cards>
      <Card name="Basic Tower" count="5" />
      <Card name="Basic Upgrade" count="5" />
      <Card name="Double-Barrel Upgrade" count="5" />
      <Card name="Fast Tower" count="5" />
      <Card name="Fast Upgrade" count="5" />
      <Card name="Light Shield" count="5" />
      <Card name="Piercing Ammo" count="5" />
      <Card name="Risky Draw" count="5" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Two Way Street.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Green_Arcs.png" backgroundTileRate="32" centerBackground="true">
  <difficulty>easy</difficulty>
  <description>Enemies travel the central path in two directions at once</description>
  <randomWaveCount>20</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="11" spawnY="-4" />
    <Spawner spawnX="-10" spawnY="-4" />
  </Spawners>
  <PathSegments>
    <Segment startX="11" startY="-4" endX="11" endY="0" />
    <Segment startX="11" startY="0" endX="-11" endY="0" />
    <Segment startX="-11" startY="0" endX="-11" endY="5" />
    <Segment startX="-10" startY="-4" endX="-10" endY="0" />
    <Segment startX="-10" startY="0" endX="10" endY="0" />
    <Segment startX="10" startY="0" endX="10" endY="5" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Challenger</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Chain.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Blue_Gradient.png" backgroundTileRate="64" >
  <difficulty>medium</difficulty>
  <description>Two paths weaving through each other.</description>
  <randomWaveCount>25</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="21" spawnY="-3" />
    <Spawner spawnX="-2" spawnY="2" />
  </Spawners>
  <PathSegments>
    <Segment startX="21" startY="-3" endX="19" endY="-3" />
    <Segment startX="19" startY="-3" endX="19" endY="3" />
    <Segment startX="19" startY="3" endX="10" endY="3" />
    <Segment startX="10" startY="3" endX="10" endY="-3" />
    <Segment startX="10" startY="-3" endX="1" endY="-3" />
    <Segment startX="1" startY="-3" endX="1" endY="3" />
    <Segment startX="1" startY="3" endX="-1" endY="3" />
    <Segment startX="-2" startY="2" endX="-2" endY="0" />
    <Segment startX="-2" startY="0" endX="4" endY="0" />
    <Segment startX="4" startY="0" endX="4" endY="-6" />
    <Segment startX="4" startY="-6" endX="7" endY="-6" />
    <Segment startX="7" startY="-6" endX="7" endY="0" />
    <Segment startX="7" startY="0" endX="13" endY="0" />
    <Segment startX="13" startY="0" endX="13" endY="6" />
    <Segment startX="13" startY="6" endX="16" endY="6" />
    <Segment startX="16" startY="6" endX="16" endY="0" />
    <Segment startX="16" startY="0" endX="22" endY="0" />
    <Segment startX="22" startY="0" endX="22" endY="-2" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Plague</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Modded Levels/Dev Performance Test.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>testing only</difficulty>
  <description>Developer map with many enemies for testing performance issues</description>
  <randomWaveCount>0</randomWaveCount>
  <Waves>
    <Wave type="Assassin" budget="10000" time="30" />
    <Wave type="Carrier" budget="10000" time="30" />
    <Wave type="Giant" budget="10000" time="30" />
    <Wave type="Ping" budget="10000" time="30" />
    <Wave type="Refurb" budget="10000" time="30" />
    <Wave type="Regenerative Tank" budget="10000" time="30" />
    <Wave type="Scrambled" budget="10000" time="30" />
    <Wave type="Standard" budget="10000" time="30" />
    <Wave type="Swarm" budget="10000" time="30" />
    <Wave type="Tank" budget="10000" time="30" />
  </Waves>
  <Spawners>
    <Spawner spawnX="0" spawnY="0" />
    <Spawner spawnX="0" spawnY="1" />
  </Spawners>
  <PathSegments>
    <Segment startX="0" startY="0" endX="0" endY="-1" />
    <Segment startX="0" startY="-1" endX="2" endY="-1" />
    <Segment startX="2" startY="-1" endX="2" endY="3" />
    <Segment startX="2" startY="3" endX="-8" endY="3" />
    <Segment startX="-8" startY="3" endX="-8" endY="-2" />
    <Segment startX="-8" startY="-2" endX="-4" endY="-2" />
    <Segment startX="-4" startY="-2" endX="-4" endY="2" />
    <Segment startX="-4" startY="2" endX="-7" endY="2" />
    <Segment startX="-7" startY="2" endX="-7" endY="-1" />
    <Segment startX="-7" startY="-1" endX="-5" endY="-1" />
    <Segment startX="-5" startY="-1" endX="-5" endY="1" />
    <Segment startX="-5" startY="1" endX="-6" endY="1" />
    <Segment startX="0" startY="1" endX="0" endY="2" />
    <Segment startX="0" startY="2" endX="-2" endY="2" />
    <Segment startX="-2" startY="2" endX="-2" endY="-2" />
    <Segment startX="-2" startY="-2" endX="8" endY="-2" />
    <Segment startX="8" startY="-2" endX="8" endY="3" />
    <Segment startX="8" startY="3" endX="4" endY="3" />
    <Segment startX="4" startY="3" endX="4" endY="-1" />
    <Segment startX="4" startY="-1" endX="7" endY="-1" />
    <Segment startX="7" startY="-1" endX="7" endY="2" />
    <Segment startX="7" startY="2" endX="5" endY="2" />
    <Segment startX="5" startY="2" endX="5" endY="0" />
    <Segment startX="5" startY="0" endX="6" endY="0" />
  </PathSegments>
  <Towers>
    <Tower name="Fast Tower" x="-6.5" y="0.5" />
    <Tower name="Fast Tower" x="-5.5" y="0.5" />
    <Tower name="Fast Tower" x="-6.5" y="-0.5" />
    <Tower name="Fast Tower" x="-5.5" y="-0.5" />
    <Tower name="Fast Tower" x="-6.5" y="0" />
    <Tower name="Fast Tower" x="-6" y="0.5" />
    <Tower name="Fast Tower" x="-6" y="-0.5" />
    <Tower name="Fast Tower" x="-5.5" y="0" />
    <Tower name="Fast Tower" x="-6" y="0" />
    <Tower name="Fast Tower" x="6.5" y="1.5" />
    <Tower name="Fast Tower" x="5.5" y="1.5" />
    <Tower name="Fast Tower" x="6.5" y="0.5" />
    <Tower name="Fast Tower" x="5.5" y="0.5" />
    <Tower name="Fast Tower" x="6.5" y="1" />
    <Tower name="Fast Tower" x="6" y="1.5" />
    <Tower name="Fast Tower" x="6" y="0.5" />
    <Tower name="Fast Tower" x="5.5" y="1" />
    <Tower name="Fast Tower" x="6" y="1" />
    <Tower name="Shredder Tower" x="-0.5" y="0">
      <Upgrades>
        <Upgrade Name="Fast Upgrade" Count="5" />
      </Upgrades>
    </Tower>
    <Tower name="Shredder Tower" x="-0.5" y="1">
      <Upgrades>
        <Upgrade Name="Fast Upgrade" Count="5" />
      </Upgrades>
    </Tower>
    <Tower name="Shredder Tower" x="0.5" y="0">
      <Upgrades>
        <Upgrade Name="Fast Upgrade" Count="5" />
      </Upgrades>
    </Tower>
    <Tower name="Shredder Tower" x="0.5" y="1">
      <Upgrades>
        <Upgrade Name="Fast Upgrade" Count="5" />
      </Upgrades>
    </Tower>
    <Tower name="Challenger Tower" x="-1" y="-5" />
    <Tower name="Challenger Tower" x="-0.5" y="-5" />
    <Tower name="Challenger Tower" x="0" y="-5" />
    <Tower name="Challenger Tower" x="0.5" y="-5" />
    <Tower name="Challenger Tower" x="1" y="-5" />
  </Towers>
  <shuffleDeck>false</shuffleDeck>
  <levelDeck name="Level Deck">
    <Cards>
      <Card name="Dev Purge Tower" count="2" />
      <Card name="Chain Hit" count="1" />
      <Card name="Gambit" count="2" />
      <Card name="Orthogonal Tower" count="2" />
      <Card name="Reinforce" count="5" />
      <Card name="Shield" count="200" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Sector G7.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>medium</difficulty>
  <description>A region with many branching paths</description>
  <randomWaveCount>30</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="7" spawnY="-5.5" />
    <Spawner spawnX="1" spawnY="-5.5" />
  </Spawners>
  <PathSegments>
    <Segment startX="7" startY="-5.5" endX="7" endY="-4.5" />
    <Segment startX="7" startY="-4.5" endX="8" endY="-4.5" />
    <Segment startX="8" startY="-4.5" endX="8" endY="2.5" />
    <Segment startX="8" startY="2.5" endX="7" endY="3.5" />
    <Segment startX="7" startY="3.5" endX="7" endY="5.5" />
    <Segment startX="7" startY="5.5" endX="5" endY="5.5" />
    <Segment startX="5" startY="5.5" endX="5" endY="3.5" />
    <Segment startX="5" startY="3.5" endX="5" endY="2.5" />
    <Segment startX="5" startY="2.5" endX="3" endY="2.5" />
    <Segment startX="3" startY="2.5" endX="2" endY="3.5" />
    <Segment startX="7" startY="3.5" endX="5" endY="3.5" />
    <Segment startX="5" startY="2.5" endX="5" endY="0.5" />
    <Segment startX="5" startY="0.5" endX="3" endY="0.5" />
    <Segment startX="3" startY="0.5" endX="3" endY="2.5" />
    <Segment startX="7" startY="-4.5" endX="5" endY="-2.5" />
    <Segment startX="5" startY="-2.5" endX="5" endY="0.5" />
    <Segment startX="2" startY="3.5" endX="2" endY="4.5" />
    <Segment startX="2" startY="4.5" endX="0" endY="4.5" />
    <Segment startX="0" startY="4.5" endX="0" endY="1.5" />
    <Segment startX="0" startY="1.5" endX="-1" endY="0.5" />
    <Segment startX="-1" startY="0.5" endX="-3" endY="0.5" />
    <Segment startX="-1" startY="0.5" endX="-1" endY="-2.5" />
    <Segment startX="1" startY="-2.5" endX="-1" endY="-2.5" />
    <Segment startX="-1" startY="-2.5" endX="-1" endY="-3.5" />
    <Segment startX="-1" startY="-3.5" endX="-2" endY="-4.5" />
    <Segment startX="-2" startY="-4.5" endX="-3" endY="-4.5" />
    <Segment startX="-3" startY="-4.5" endX="-4" endY="-3.5" />
    <Segment startX="-4" startY="-3.5" endX="-4" endY="0.5" />
    <Segment startX="-4" startY="0.5" endX="-4" endY="1.5" />
    <Segment startX="-4" startY="1.5" endX="-6" endY="1.5" />
    <Segment startX="-6" startY="1.5" endX="-8" endY="1.5" />
    <Segment startX="-8" startY="1.5" endX="-8" endY="-1.5" />
    <Segment startX="-8" startY="-1.5" endX="-6" endY="-3.5" />
    <Segment startX="-6" startY="-3.5" endX="-6" endY="-5.5" />
    <Segment startX="-4" startY="1.5" endX="-4" endY="3.5" />
    <Segment startX="-4" startY="3.5" endX="-6" endY="3.5" />
    <Segment startX="-6" startY="3.5" endX="-6" endY="1.5" />
    <Segment startX="1" startY="-5.5" endX="1" endY="-4.5" />
    <Segment startX="1" startY="-4.5" endX="3" endY="-4.5" />
    <Segment startX="3" startY="-4.5" endX="5" endY="-2.5" />
    <Segment startX="1" startY="-4.5" endX="1" endY="-2.5" />
    <Segment startX="-3" startY="0.5" endX="-4" endY="0.5" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Endurance</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Modded Levels/Dev Tower Test.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <description>Developer map with all types of towers</description>
  <randomWaveCount>10</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="-5" spawnY="5" />
    <Spawner spawnX="0" spawnY="5" />
    <Spawner spawnX="5" spawnY="5" />
  </Spawners>
  <PathSegments>
    <Segment startX="-5" startY="5" endX="-5" endY="-4" />
    <Segment startX="0" startY="5" endX="0" endY="-4" />
    <Segment startX="5" startY="5" endX="5" endY="-4" />
    <Segment startX="-5" startY="-4" endX="8" endY="-4" />
    <Segment startX="0" startY="-4" endX="8" endY="-4" />
    <Segment startX="5" startY="-4" endX="8" endY="-4" />
    <Segment startX="8" startY="-4" endX="8" endY="3" />
  </PathSegments>
  <Towers>
    <Tower name="AOE Tower" x="5" y="-6" />
    <Tower name="Basic Tower" x="5.5" y="-6" />
    <Tower name="Black Plague Tower" x="6" y="-6" />
    <Tower name="Challenger Tower" x="6.5" y="-6" />
    <Tower name="Dev Chain Purge Tower" x="7" y="-6" />
    <Tower name="Dev Purge Tower" x="7.5" y="-6" />
    <Tower name="Explosive Tower" x="8" y="-6" />
    <Tower name="Fast Tower" x="8.5" y="-6" />
    <Tower name="Heavy Tower" x="5" y="-8" />
    <Tower name="Nova Tower" x="5.5" y="-8" />
    <Tower name="Orthogonal Tower" x="6" y="-8" />
    <Tower name="Overcharge Tower" x="6.5" y="-8" />
    <Tower name="Plague Tower" x="7" y="-8" />
    <Tower name="Shredder Tower" x="7.5" y="-8" />
    <Tower name="Sniper Tower" x="8" y="-8" />
    <Tower name="Supernova Tower" x="8.5" y="-8" />
    <Tower name="Dev Purge Tower" x="8.5" y="2.5" />
    <Tower name="Mouse Tower" x="9" y="-6" />
  </Towers>
  <shuffleDeck>true</shuffleDeck>
  <levelDeck name="Level Deck">
    <Cards>
      <Card name="AOE Tower" count="2" />
      <Card name="Basic Tower" count="2" />
      <Card name="Black Plague Tower" count="2" />
      <Card name="Challenger Tower" count="2" />
      <Card name="Dev Chain Purge Tower" count="2" />
      <Card name="Dev Purge Tower" count="2" />
      <Card name="Explosive Tower" count="2" />
      <Card name="Fast Tower" count="2" />
      <Card name="Heavy Tower" count="2" />
      <Card name="Mouse Tower" count="2" />
      <Card name="Nova Tower" count="2" />
      <Card name="Orthogonal Tower" count="2" />
      <Card name="Overcharge Tower" count="2" />
      <Card name="Plague Tower" count="2" />
      <Card name="Shredder Tower" count="2" />
      <Card name="Sniper Tower" count="2" />
      <Card name="Supernova Tower" count="2" />
    </Cards>
  </levelDeck>
</Level>
