=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Level.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xsd:element name="Level">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="difficulty" type="xsd:string" />
        <xsd:element name="description" type="xsd:string" />
        <xsd:element name="randomWaveCount" type="xsd:unsignedByte" />
        <xsd:element name="waveGrowthAbsolute" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthLinear" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthSquared" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthExponential" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveTimeLinear" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveTimeMax" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="disableGatherPower" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="Waves">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" minOccurs="0" name ="Wave">
                <xsd:complexType>
                  <xsd:attribute name="type" type="xsd:string" use="required" />
                  <xsd:attribute name="budget" type="xsd:int" use="required" />
                  <xsd:attribute name="time" type="xsd:float" use="required" />
                  <xsd:attribute name="message" type="xsd:string" use="optional" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Spawners">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Spawner">
                <xsd:complexType>
                  <xsd:attribute name="spawnX" type="xsd:float" use="required" />
                  <xsd:attribute name="spawnY" type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="PathSegments">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Segment">
                <xsd:complexType>
                  <xsd:attribute name="startX" type="xsd:float" use="required" />
                  <xsd:attribute name="startY" type="xsd:float" use="required" />
                  <xsd:attribute name="endX"   type="xsd:float" use="required" />
                  <xsd:attribute name="endY"   type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Towers">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Tower" maxOccurs="unbounded" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Upgrades" maxOccurs="unbounded" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="Upgrade" maxOccurs="unbounded" minOccurs="0">
                            <xsd:complexType>
                              <xsd:attribute name="Name" type="xsd:string" use="required" />
                              <xsd:attribute name="Count" type="xsd:unsignedByte" use="required" />
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="name" type="xsd:string" use="required" />
                  <xsd:attribute name="x" type="xsd:float" use="required" />
                  <xsd:attribute name="y" type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="shuffleDeck" type="xsd:boolean"/>
        <xsd:choice>
          <xsd:element name="levelDeck">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="Cards">
                  <xsd:complexType>
                    <xsd:sequence>
                      <xsd:element maxOccurs="unbounded" name="Card">
                        <xsd:complexType>
                          <xsd:attribute name="name" type="xsd:string" use="required" />
                          <xsd:attribute name="count" type="xsd:unsignedByte" use="required" />
                        </xsd:complexType>
                      </xsd:element>
                    </xsd:sequence>
                  </xsd:complexType>
                </xsd:element>
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="premadeDeckName" type="xsd:string" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="background" type="xsd:string" />
      <xsd:attribute name="backgroundTileRate" type="xsd:float" />
      <xsd:attribute name="centerBackground" type="xsd:boolean" use="optional" />
      <xsd:attribute name="cardFileDependencies" type="xsd:string" use="optional" />
      <xsd:attribute name="enemyFileDependencies" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
</xs:schema>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/theta.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>hard</difficulty>
  <description>8th letter of the greek alphabet</description>
  <randomWaveCount>20</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="0.5" spawnY="0" />
    <Spawner spawnX="-0.5" spawnY="0" />
  </Spawners>
  <PathSegments>
    <Segment startX="0.5" startY="0" endX="4" endY="0" />
    <Segment startX="4" startY="0" endX="4" endY="4" />
    <Segment startX="4" startY="4" endX="3" endY="4" />
    <Segment startX="3" startY="4" endX="3" endY="6" />
    <Segment startX="3" startY="6" endX="2" endY="6" />
    <Segment startX="2" startY="6" endX="2" endY="8" />
    <Segment startX="2" startY="8" endX="0" endY="8" />
    <Segment startX="4" startY="0" endX="4" endY="-4" />
    <Segment startX="4" startY="-4" endX="3" endY="-4" />
    <Segment startX="3" startY="-4" endX="3" endY="-6" />
    <Segment startX="3" startY="-6" endX="2" endY="-6" />
    <Segment startX="2" startY="-6" endX="2" endY="-8" />
    <Segment startX="2" startY="-8" endX="0" endY="-8" />
    <Segment startX="-0.5" startY="0" endX="-4" endY="0" />
    <Segment startX="-4" startY="0" endX="-4" endY="4" />
    <Segment startX="-4" startY="4" endX="-3" endY="4" />
    <Segment startX="-3" startY="4" endX="-3" endY="6" />
    <Segment startX="-3" startY="6" endX="-2" endY="6" />
    <Segment startX="-2" startY="6" endX="-2" endY="8" />
    <Segment startX="-2" startY="8" endX="0" endY="8" />
    <Segment startX="-4" startY="0" endX="-4" endY="-4" />
    <Segment startX="-4" startY="-4" endX="-3" endY="-4" />
    <Segment startX="-3" startY="-4" endX="-3" endY="-6" />
    <Segment startX="-3" startY="-6" endX="-2" endY="-6" />
    <Segment startX="-2" startY="-6" endX="-2" endY="-8" />
    <Segment startX="-2" startY="-8" endX="0" endY="-8" />
  </PathSegments>
  <Towers>
    <Tower name="Sniper Tower" x="0" y="0">
      <Upgrades>
        <Upgrade Name="Heavy Upgrade" Count="1" />
        <Upgrade Name="Spitfire Upgrade" Count="1" />
        <Upgrade Name="Manual Control" Count="1" />
      </Upgrades>
    </Tower>
  </Towers>
  <shuffleDeck>true</shuffleDeck>
  <levelDeck name="Theta Deck">
    <Cards>
      <Card name="Basic Tower" count="6" />
      <Card name="Basic Upgrade" count="4" />
      <Card name="Enrage" count="2" />
      <Card name="Fast Tower" count="8" />
      <Card name="Fast Upgrade" count="8" />
      <Card name="Heavy Tower" count="4" />
      <Card name="Heavy Upgrade" count="4" />
      <Card name="Infrastructure Funding" count="5" />
      <Card name="Light Shield" count="3" />
      <Card name="Reinforce" count="2" />
      <Card name="Scavenge" count="3" />
      <Card name="Summon Swarm" count="1" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Trophy.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>medium</difficulty>
  <description>A nice place to try fighting large crowds for the fist time.</description>
  <randomWaveCount>25</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="6" spawnY="-6" />
  </Spawners>
  <PathSegments>
    <Segment startX="6" startY="-6" endX="12" endY="-6" />
    <Segment startX="12" startY="-6" endX="12" endY="-5" />
    <Segment startX="12" startY="-5" endX="6" endY="-5" />
    <Segment startX="6" startY="-5" endX="6" endY="-3" />
    <Segment startX="6" startY="-3" endX="8" endY="-3" />
    <Segment startX="8" startY="-3" endX="8" endY="-2" />
    <Segment startX="8" startY="-2" endX="10" endY="-2" />
    <Segment startX="10" startY="-2" endX="10" endY="-1" />
    <Segment startX="10" startY="-1" endX="12" endY="-1" />
    <Segment startX="12" startY="-1" endX="12" endY="1" />
    <Segment startX="12" startY="1" endX="13" endY="1" />
    <Segment startX="13" startY="1" endX="13" endY="3" />
    <Segment startX="13" startY="3" endX="14" endY="3" />
    <Segment startX="14" startY="3" endX="14" endY="10" />
    <Segment startX="14" startY="10" endX="-3" endY="10" />
    <Segment startX="-3" startY="10" endX="-3" endY="3" />
    <Segment startX="-3" startY="3" endX="-2" endY="3" />
    <Segment startX="-2" startY="3" endX="-2" endY="1" />
    <Segment startX="-2" startY="1" endX="-1" endY="1" />
    <Segment startX="-1" startY="1" endX="-1" endY="-1" />
    <Segment startX="-1" startY="-1" endX="1" endY="-1" />
    <Segment startX="1" startY="-1" endX="1" endY="-2" />
    <Segment startX="1" startY="-2" endX="3" endY="-2" />
    <Segment startX="3" startY="-2" endX="3" endY="-3" />
    <Segment startX="3" startY="-3" endX="5" endY="-3" />
    <Segment startX="5" startY="-3" endX="5" endY="-5" />
    <Segment startX="5" startY="-5" endX="-1" endY="-5" />
    <Segment startX="-1" startY="-5" endX="-1" endY="-6" />
    <Segment startX="-1" startY="-6" endX="5" endY="-6" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Challenger</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Switchback.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Cyan_Vortex.png" backgroundTileRate="32" centerBackground="true">
  <difficulty>easy</difficulty>
  <description>Enemies finish near where they begin</description>
  <randomWaveCount>25</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="-2" spawnY="-4.5" />
  </Spawners>
  <PathSegments>
    <Segment startX="-2" startY="-4.5" endX="-2" endY="3.5" />
    <Segment startX="-2" startY="3.5" endX="4" endY="3.5" />
    <Segment startX="4" startY="3.5" endX="4" endY="-0.5" />
    <Segment startX="4" startY="-0.5" endX="-5" endY="-0.5" />
    <Segment startX="-5" startY="-0.5" endX="-5" endY="4.5" />
    <Segment startX="-5" startY="4.5" endX="5" endY="4.5" />
    <Segment startX="5" startY="4.5" endX="5" endY="-1.5" />
    <Segment startX="5" startY="-1.5" endX="-3" endY="-1.5" />
    <Segment startX="-3" startY="-1.5" endX="-3" endY="-4.5" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Starter Deck</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Divergence 2.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>hard</difficulty>
  <description>A very challenging map with 18 points to defend</description>
  <randomWaveCount>20</randomWaveCount>
  <waveGrowthAbsolute>30</waveGrowthAbsolute>
  <waveGrowthLinear>6</waveGrowthLinear>
  <waveGrowthSquared>2</waveGrowthSquared>
  <waveGrowthExponential>1</waveGrowthExponential>
  <waveTimeLinear>1</waveTimeLinear>
  <Waves />
  <Spawners>
    <Spawner spawnX="10" spawnY="0" />
  </Spawners>
  <PathSegments>
    <Segment startX="10" startY="0" endX="6" endY="0" />
    <Segment startX="6" startY="0" endX="6" endY="4" />
    <Segment startX="6" startY="0" endX="4" endY="0" />
    <Segment startX="4" startY="0" endX="4" endY="4" />
    <Segment startX="4" startY="0" endX="2" endY="0" />
    <Segment startX="2" startY="0" endX="2" endY="4" />
    <Segment startX="2" startY="0" endX="0" endY="0" />
    <Segment startX="0" startY="0" endX="0" endY="4" />
    <Segment startX="0" startY="0" endX="-2" endY="0" />
    <Segment startX="-2" startY="0" endX="-2" endY="4" />
    <Segment startX="-2" startY="0" endX="-4" endY="0" />
    <Segment startX="-4" startY="0" endX="-4" endY="4" />
    <Segment startX="-4" startY="0" endX="-6" endY="0" />
    <Segment startX="-6" startY="0" endX="-6" endY="4" />
    <Segment startX="-6" startY="0" endX="-8" endY="0" />
    <Segment startX="-8" startY="0" endX="-8" endY="4" />
    <Segment startX="-8" startY="0" endX="-10" endY="0" />
    <Segment startX="-10" startY="0" endX="-10" endY="4" />
    <Segment startX="6" startY="0" endX="6" endY="-4" />
    <Segment startX="4" startY="0" endX="4" endY="-4" />
    <Segment startX="2" startY="0" endX="2" endY="-4" />
    <Segment startX="0" startY="0" endX="0" endY="-4" />
    <Segment startX="-2" startY="0" endX="-2" endY="-4" />
    <Segment startX="-4" startY="0" endX="-4" endY="-4" />
    <Segment startX="-6" startY="0" endX="-6" endY="-4" />
    <Segment startX="-8" startY="0" endX="-8" endY="-4" />
    <Segment startX="-10" startY="0" endX="-10" endY="-4" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Endurance</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Pi.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>hard</difficulty>
  <description>Enemies here are markedly stronger than usual</description>
  <randomWaveCount>25</randomWaveCount>
  <waveGrowthLinear>10</waveGrowthLinear>
  <waveGrowthSquared>3.14159</waveGrowthSquared>
  <waveGrowthExponential>1.15</waveGrowthExponential>
  <Waves />
  <Spawners>
    <Spawner spawnX="-6" spawnY="4" />
  </Spawners>
  <PathSegments>
    <Segment startX="-6" startY="4" endX="-5" endY="5" />
    <Segment startX="-5" startY="5" endX="-2" endY="5" />
    <Segment startX="-2" startY="5" endX="-2" endY="-2" />
    <Segment startX="-2" startY="-2" endX="-3" endY="-3" />
    <Segment startX="-3" startY="-3" endX="-4" endY="-2" />
    <Segment startX="-4" startY="-2" endX="-3" endY="-1" />
    <Segment startX="-2" startY="5" endX="2" endY="5" />
    <Segment startX="2" startY="5" endX="2" endY="-2" />
    <Segment startX="2" startY="-2" endX="3" endY="-4" />
    <Segment startX="3" startY="-4" endX="4" endY="-5" />
    <Segment startX="4" startY="-5" endX="5" endY="-5" />
    <Segment startX="5" startY="-5" endX="6" endY="-3" />
    <Segment startX="2" startY="5" endX="5" endY="5" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <levelDeck name="New Deck">
    <Cards>
      <Card name="Basic Tower" count="4" />
      <Card name="Basic Upgrade" count="5" />
      <Card name="Challenger Tower" count="3" />
      <Card name="Fast Tower" count="4" />
      <Card name="Fast Upgrade" count="10" />
      <Card name="Heavy Tower" count="5" />
      <Card name="Heavy Upgrade" count="4" />
      <Card name="Life Tap" count="3" />
      <Card name="Light Shield" count="4" />
      <Card name="Plague Tower" count="2" />
      <Card name="Quad-Barrel Upgrade" count="2" />
      <Card name="Resonant Tower (P)" count="10" />
      <Card name="Summon Swarm" count="4" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Tutorial 1 The Basics.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black_WhiteGridDottedLines.png" backgroundTileRate="1">
  <difficulty>Tutorials</difficulty>
  <description>Learn the basics of how to play the game</description>
  <randomWaveCount>0</randomWaveCount>
  <disableGatherPower>true</disableGatherPower> <!--disable gather power for this tutorial-->
  <Waves>
    <Wave type="Standard" budget="64" time="1.1" message="Welcome to Card Defense!  In this game, your goal is to use the cards in your deck to fight off all of the enemies.  To do this, you will need to use the yellow cards in your hand to build towers.  Start by playing one of your 'Basic Tower' cards.  First, click on a card that says 'Basic Tower', then click somewhere on the map to build it there.  When building, the yellow circle shows the range of the tower.  You want to place the tower so that the circle covers as much path as possible.  One should be enough to fend off this first wave, but feel free to build a second if you want to be on the safe side.  After you are done building, click 'Start Wave' at the top of the screen or press the spacebar to start the round, and watch the action." />
    <Wave type="Standard" budget="87" time="2.2" message="As you have seen, at the end of each round both you and the enemies draw one card from your respective decks.  Also notice that the number in the middle of your towers went down by one.  This is the 'lifespan' of your tower, and if it hits zero then that tower will disappear forever.  Because of this, it is important not to build more towers than you think you need!  You will likely need them later in the level as the enemy waves get stronger.  If your towers easily defeated the previous wave, you should be able to start this one without building anything else.  If they struggled, however, or if some of them survived, then go ahead and build another Basic tower to shore up your defenses."/>
    <Wave type="Tank" budget="119" time="3.30000019" message="This next enemy is called a 'Tank'.  Once you close this window, you can hover your mouse above the enemy card at the top screen to get a closer look.  Note that it has a lot of heatlh, and 15 points of armor.  The armor means every attack made against that enemy will do 15 less damage, so you want some towers that hit hard.  Play both of your 'Heavy Tower' cards to help fight it off.  (By the way, if the game is moving too slow for you, you can speed it up with the controls at the top of the screen"/>
    <Wave type="Swarm" budget="213" time="4.4" message="These enemies are called 'Swarms'.  They are very weak, but there are a lot of them, and they move quickly.  Your heavy towers will be almost useless here, since they will kill one enemy and the others will just walk on by while the towers are recharging.  Instead, play both of your 'Fast Tower's.  These towers are weak, but they attack very quickly, making them better suited to this task.  (By the way, you can move the camera around with the arrow keys or WASD, and you can zoom it in or out with your scroll wheel or by pressing Q or E."/>
    <Wave type="Giant" budget="250" time="5.5" message="This enemy is a 'Giant', which is a single, very difficult, enemy.  For this wave, I recommend playing the green upgrade cards in your hand.  These cards upgrade towers you have already built so that they are stronger and last longer.  I suggest playing your Heavy Upgrades on your Heavy Towers.  You should also decide what to use your Fast Upgrades on: the Fast Towers will get a greater benefit from them, but you might want to use them on Basic Towers instead to stop them from disappearing.  The choice is yours."/>
    <Wave type="Standard" budget="300" time="6" message="If you look at the enemy deck in the upper right corner of your screen, you will see that they are now out of cards, so this is the last wave in the level: after this, you have won!  Feel free to play your entire hand now.  After all, there is no 'later' to save them for any more.  After you win, you will be asked if you want to 'continue in endurance'.  If you say yes, then the level will continue, throwing more and more enemies at you until you die.  You can do this if you want, or you can say no to return to the menu."/>
  </Waves>
  <Spawners>
    <Spawner spawnX="9.5" spawnY="-1" />
  </Spawners>
  <PathSegments>
    <Segment startX="9.5" startY="-1" endX="4.5" endY="-1" />
    <Segment startX="4.5" startY="-1" endX="4.5" endY="0" />
    <Segment startX="4.5" startY="-1" endX="4.5" endY="-2" />
    <Segment startX="4.5" startY="0" endX="0.5" endY="0" />
    <Segment startX="0.5" startY="0" endX="0.5" endY="-1" />
    <Segment startX="4.5" startY="-2" endX="0.5" endY="-2" />
    <Segment startX="0.5" startY="-2" endX="0.5" endY="-1" />
    <Segment startX="4.5" startY="-1" endX="0.5" endY="-1" />
    <Segment startX="0.5" startY="-1" endX="-1.5" endY="-1" />
    <Segment startX="-1.5" startY="-1" endX="-1.5" endY="3" />
    <Segment startX="-1.5" startY="3" endX="-9.5" endY="3" />
    <Segment startX="-9.5" startY="3" endX="-9.5" endY="-3" />
    <Segment startX="-9.5" startY="-3" endX="-5.5" endY="-3" />
    <Segment startX="-5.5" startY="-3" endX="-5.5" endY="1" />
    <Segment startX="-5.5" startY="1" endX="-7.5" endY="1" />
  </PathSegments>
  <Towers />
  <shuffleDeck>false</shuffleDeck>
  <levelDeck name="Tutorial Deck">
    <Cards>
      <Card name="Basic Tower" count="4" />
      <Card name="Heavy Tower" count="2" />
      <Card name="Fast Tower" count="2" />
      <Card name="Fast Upgrade" count="2" />
      <Card name="Heavy Upgrade" count="2" />
      <Card name="Light Shield" count="2" />
      <Card name="Life Tap" count="1" />
      <Card name="Enrage" count="2" />
      <Card name="Challenger Tower" count="2" />
      <Card name="AOE Tower" count="1" />
      <Card name="Piercing Ammo" count="1" />
      <Card name="Fast Upgrade" count="3" />
      <Card name="Heavy Upgrade" count="3" />
      <Card name="Light Shield" count="3" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Symmetry.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd"  background="Blue_Gradient.png" backgroundTileRate="64" >
  <difficulty>medium</difficulty>
  <description>Two symmetrical spirals.  The default level deck here contains no towers.</description>
  <randomWaveCount>19</randomWaveCount>
  <Waves>
    <Wave type="Standard" budget="116" time="1.1" />
  </Waves>
  <Spawners>
    <Spawner spawnX="0" spawnY="-0.5" />
    <Spawner spawnX="0" spawnY="0.5" />
  </Spawners>
  <PathSegments>
    <Segment startX="0" startY="-0.5" endX="0" endY="-1.5" />
    <Segment startX="0" startY="-1.5" endX="2" endY="-1.5" />
    <Segment startX="2" startY="-1.5" endX="2" endY="2.5" />
    <Segment startX="2" startY="2.5" endX="-8" endY="2.5" />
    <Segment startX="-8" startY="2.5" endX="-8" endY="-2.5" />
    <Segment startX="-8" startY="-2.5" endX="-4" endY="-2.5" />
    <Segment startX="-4" startY="-2.5" endX="-4" endY="1.5" />
    <Segment startX="-4" startY="1.5" endX="-7" endY="1.5" />
    <Segment startX="-7" startY="1.5" endX="-7" endY="-1.5" />
    <Segment startX="-7" startY="-1.5" endX="-5" endY="-1.5" />
    <Segment startX="-5" startY="-1.5" endX="-5" endY="0.5" />
    <Segment startX="-5" startY="0.5" endX="-6" endY="0.5" />
    <Segment startX="0" startY="0.5" endX="0" endY="1.5" />
    <Segment startX="0" startY="1.5" endX="-2" endY="1.5" />
    <Segment startX="-2" startY="1.5" endX="-2" endY="-2.5" />
    <Segment startX="-2" startY="-2.5" endX="8" endY="-2.5" />
    <Segment startX="8" startY="-2.5" endX="8" endY="2.5" />
    <Segment startX="8" startY="2.5" endX="4" endY="2.5" />
    <Segment startX="4" startY="2.5" endX="4" endY="-1.5" />
    <Segment startX="4" startY="-1.5" endX="7" endY="-1.5" />
    <Segment startX="7" startY="-1.5" endX="7" endY="1.5" />
    <Segment startX="7" startY="1.5" endX="5" endY="1.5" />
    <Segment startX="5" startY="1.5" endX="5" endY="-0.5" />
    <Segment startX="5" startY="-0.5" endX="6" endY="-0.5" />
  </PathSegments>
  <Towers>
    <Tower name="Heavy Tower" x="-6.5" y="0" />
    <Tower name="Heavy Tower" x="-5.5" y="0" />
    <Tower name="Heavy Tower" x="-6.5" y="-1" />
    <Tower name="Heavy Tower" x="-5.5" y="-1" />
    <Tower name="Fast Tower" x="-6.5" y="-0.5" />
    <Tower name="Fast Tower" x="-6" y="0" />
    <Tower name="Fast Tower" x="-6" y="-1" />
    <Tower name="Fast Tower" x="-5.5" y="-0.5" />
    <Tower name="Basic Tower" x="-6" y="-0.5" />
    <Tower name="Heavy Tower" x="6.5" y="1" />
    <Tower name="Heavy Tower" x="5.5" y="1" />
    <Tower name="Heavy Tower" x="6.5" y="0" />
    <Tower name="Heavy Tower" x="5.5" y="0" />
    <Tower name="Fast Tower" x="6.5" y="0.5" />
    <Tower name="Fast Tower" x="6" y="1" />
    <Tower name="Fast Tower" x="6" y="0" />
    <Tower name="Fast Tower" x="5.5" y="0.5" />
    <Tower name="Basic Tower" x="6" y="0.5" />
  </Towers>
  <shuffleDeck>true</shuffleDeck>
  <levelDeck name="Level Deck">
    <Cards>
      <Card name="Enrage" count="4" />
      <Card name="Fast Upgrade" count="10" />
      <Card name="Heavy Upgrade" count="10" />
      <Card name="Recycle" count="3" />
      <Card name="Shield" count="3" />
    </Cards>
  </levelDeck>
</Level>
