=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Level.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xsd:element name="Level">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="difficulty" type="xsd:string" />
        <xsd:element name="description" type="xsd:string" />
        <xsd:element name="randomWaveCount" type="xsd:unsignedByte" />
        <xsd:element name="waveGrowthAbsolute" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthLinear" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthSquared" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveGrowthExponential" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveTimeLinear" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="waveTimeMax" type="xsd:float" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="disableGatherPower" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="Waves">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" minOccurs="0" name ="Wave">
                <xsd:complexType>
                  <xsd:attribute name="type" type="xsd:string" use="required" />
                  <xsd:attribute name="budget" type="xsd:int" use="required" />
                  <xsd:attribute name="time" type="xsd:float" use="required" />
                  <xsd:attribute name="message" type="xsd:string" use="optional" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Spawners">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Spawner">
                <xsd:complexType>
                  <xsd:attribute name="spawnX" type="xsd:float" use="required" />
                  <xsd:attribute name="spawnY" type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="PathSegments">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element maxOccurs="unbounded" name="Segment">
                <xsd:complexType>
                  <xsd:attribute name="startX" type="xsd:float" use="required" />
                  <xsd:attribute name="startY" type="xsd:float" use="required" />
                  <xsd:attribute name="endX"   type="xsd:float" use="required" />
                  <xsd:attribute name="endY"   type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Towers">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Tower" maxOccurs="unbounded" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Upgrades" maxOccurs="unbounded" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="Upgrade" maxOccurs="unbounded" minOccurs="0">
                            <xsd:complexType>
                              <xsd:attribute name="Name" type="xsd:string" use="required" />
                              <xsd:attribute name="Count" type="xsd:unsignedByte" use="required" />
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="name" type="xsd:string" use="required" />
                  <xsd:attribute name="x" type="xsd:float" use="required" />
                  <xsd:attribute name="y" type="xsd:float" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="shuffleDeck" type="xsd:boolean"/>
        <xsd:choice>
          <xsd:element name="levelDeck">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="Cards">
                  <xsd:complexType>
                    <xsd:sequence>
                      <xsd:element maxOccurs="unbounded" name="Card">
                        <xsd:complexType>
                          <xsd:attribute name="name" type="xsd:string" use="required" />
                          <xsd:attribute name="count" type="xsd:unsignedByte" use="required" />
                        </xsd:complexType>
                      </xsd:element>
                    </xsd:sequence>
                  </xsd:complexType>
                </xsd:element>
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="premadeDeckName" type="xsd:string" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="background" type="xsd:string" />
      <xsd:attribute name="backgroundTileRate" type="xsd:float" />
      <xsd:attribute name="centerBackground" type="xsd:boolean" use="optional" />
      <xsd:attribute name="cardFileDependencies" type="xsd:string" use="optional" />
      <xsd:attribute name="enemyFileDependencies" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
</xs:schema>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Tutorial 3 Gathering Power.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black_WhiteGridDottedLines.png" backgroundTileRate="1">
  <difficulty>Tutorials</difficulty>
  <description>Learn about the 'Gather Power' card and resource management</description>
  <randomWaveCount>0</randomWaveCount>
  <Waves>
    <Wave type="Swarm" budget="64" time="0.732879937" message="it is time to talk about a special card called 'Gather Power'.  This card does not come from your deck, and you never draw it.  Instead, a copy is given to you at the start of every round, if you don't already have one.  It has many uses, but the most important is for dealing with situations like this: you have nothing in your hand that would be a good response to the incoming enemies.  Play 'Gather Power' in order to try and draw something more helpful." />
    <Wave type="Swarm" budget="87" time="1.08427548" message="There you go.  Those fast towers should be able to handle the Swarms.  Notice that this also drew another card from the enemy deck.  In other words, the downside to 'Gather Power' is that you will have to deal with about twice as many enemies as you did before.  That being said, since you draw TWO cards from it, the reward is usually worth the risk.  " />
    <Wave type="Swarm" budget="119" time="3.30000019" message="Another reason you might want to 'Gather Power' often is it allows you to finish levels faster.  For example, in this level the enemy deck has 15 cards.  Normally, it would take 15 rounds to win.  However, if you cast 'Gather Power' every round, the enemy will play two cards each time, so you can finish in only eight rounds.  This means you won't be losing as many towers to decay.  Go ahead and use it again." />
    <Wave type="Tank" budget="161" time="4.4" />
    <Wave type="Regenerative Tank" budget="213" time="5.5" message="There are other cards with similar effects.  For example, Challenger Towers are very strong but cause both you and the enemy to draw extra cards every round.  There is also the spell Enrage, which gives the enemy two cards and you three.  Just to show you how crowded it can get, play every card in your hand.  If something lets you draw more cards, play those too." />
    <Wave type="Ping" budget="274" time="6.60000038" message="Just so you know, the enemy hand can hold 10 cards, and your hand can hold 15.  Even if someone is supposed to draw but can't for any reason, other effects on the card still happen.  (For example, if you play 'Gather Power' when the enemy deck is empty you still get to draw cards, even though the enemy couldn't do so)"/>
    <Wave type="Assassin" budget="345" time="7.70000029" />
    <Wave type="Armored" budget="426" time="8.8" />
    <Wave type="Ping" budget="516" time="9.900001"  />
    <Wave type="Assassin" budget="617" time="11" />
    <Wave type="Giant" budget="726" time="12.1" message="The Nova Tower you just drew will be very helpful for dealing with this round.  It can only fire once, but it will cause massive damage to everything in range.  Wait for it to start sparkling before starting the round, and then click on it when a lot of enemies are in range of it to watch the carnage.  you should also build several other towers to fend off anything that survives the explosion."/>
    <Wave type="Ping" budget="846" time="13.2000008" />
    <Wave type="Scrambled" budget="975" time="14.3" />
    <Wave type="Standard" budget="1114" time="15.4000006" />
  </Waves>
  <Spawners>
    <Spawner spawnX="9.5" spawnY="-1" />
  </Spawners>
  <PathSegments>
    <Segment startX="9.5" startY="-1" endX="4.5" endY="-1" />
    <Segment startX="4.5" startY="-1" endX="4.5" endY="0" />
    <Segment startX="4.5" startY="-1" endX="4.5" endY="-2" />
    <Segment startX="4.5" startY="0" endX="0.5" endY="0" />
    <Segment startX="0.5" startY="0" endX="0.5" endY="-1" />
    <Segment startX="4.5" startY="-2" endX="0.5" endY="-2" />
    <Segment startX="0.5" startY="-2" endX="0.5" endY="-1" />
    <Segment startX="4.5" startY="-1" endX="0.5" endY="-1" />
    <Segment startX="0.5" startY="-1" endX="-1.5" endY="-1" />
    <Segment startX="-1.5" startY="-1" endX="-1.5" endY="3" />
    <Segment startX="-1.5" startY="3" endX="-9.5" endY="3" />
    <Segment startX="-9.5" startY="3" endX="-9.5" endY="-3" />
    <Segment startX="-9.5" startY="-3" endX="-5.5" endY="-3" />
    <Segment startX="-5.5" startY="-3" endX="-5.5" endY="1" />
    <Segment startX="-5.5" startY="1" endX="-7.5" endY="1" />
  </PathSegments>
  <Towers />
  <shuffleDeck>false</shuffleDeck>
  <levelDeck name="Tutorial Deck">
    <Cards>
      <Card name="Heavy Tower" count="4" />
      <Card name="Heavy Upgrade" count="2" />
      <Card name="Sniper Tower" count="2" />
      <Card name="Fast Tower" count="2" />
      <Card name="Heavy Upgrade" count="3" />
      <Card name="Challenger Tower" count="2" />
      <Card name="Enrage" count="2" />
      <Card name="Challenger Tower" count="2" />
      <Card name="Nova Tower" count="1" />
      <Card name="Piercing Ammo" count="1" />
      <Card name="Fast Upgrade" count="3" />
      <Card name="Heavy Upgrade" count="3" />
      <Card name="Light Shield" count="3" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Boxes.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Multicolor_Arcs.png" backgroundTileRate="32" centerBackground="true">
  <difficulty>medium</difficulty>
  <description>Enemies climbing the pile.</description>
  <randomWaveCount>20</randomWaveCount>
  <waveGrowthLinear>5</waveGrowthLinear>
  <waveGrowthSquared>2.4</waveGrowthSquared>
  <waveTimeLinear>1.3</waveTimeLinear>
  <waveTimeMax>25</waveTimeMax>
  <Waves />
  <Spawners>
    <Spawner spawnX="-6" spawnY="-8.5" />
    <Spawner spawnX="-6" spawnY="-8.5" />
    <Spawner spawnX="-6" spawnY="-8.5" />
    <Spawner spawnX="-2" spawnY="-8.5" />
    <Spawner spawnX="-2" spawnY="-8.5" />
    <Spawner spawnX="-2" spawnY="-8.5" />
    <Spawner spawnX="2" spawnY="-8.5" />
    <Spawner spawnX="2" spawnY="-8.5" />
    <Spawner spawnX="2" spawnY="-8.5" />
    <Spawner spawnX="6" spawnY="-8.5" />
    <Spawner spawnX="6" spawnY="-8.5" />
    <Spawner spawnX="6" spawnY="-8.5" />
  </Spawners>
  <PathSegments>
    <Segment startX="-6" startY="-8.5" endX="-8" endY="-7.5" />
    <Segment startX="-8" startY="-7.5" endX="-8" endY="-4.5" />
    <Segment startX="-8" startY="-4.5" endX="-6" endY="-3.5" />
    <Segment startX="-6" startY="-8.5" endX="-4" endY="-7.5" />
    <Segment startX="-4" startY="-7.5" endX="-4" endY="-4.5" />
    <Segment startX="-4" startY="-4.5" endX="-6" endY="-3.5" />
    <Segment startX="-6" startY="-8.5" endX="-6" endY="-5.5" />
    <Segment startX="-6" startY="-5.5" endX="-4" endY="-4.5" />
    <Segment startX="-6" startY="-5.5" endX="-8" endY="-4.5" />
    <Segment startX="-2" startY="-8.5" endX="-4" endY="-7.5" />
    <Segment startX="-4" startY="-7.5" endX="-4" endY="-4.5" />
    <Segment startX="-4" startY="-4.5" endX="-2" endY="-3.5" />
    <Segment startX="-2" startY="-8.5" endX="0" endY="-7.5" />
    <Segment startX="0" startY="-7.5" endX="0" endY="-4.5" />
    <Segment startX="0" startY="-4.5" endX="-2" endY="-3.5" />
    <Segment startX="-2" startY="-8.5" endX="-2" endY="-5.5" />
    <Segment startX="-2" startY="-5.5" endX="-4" endY="-4.5" />
    <Segment startX="-2" startY="-5.5" endX="0" endY="-4.5" />
    <Segment startX="2" startY="-8.5" endX="0" endY="-7.5" />
    <Segment startX="0" startY="-4.5" endX="2" endY="-3.5" />
    <Segment startX="2" startY="-8.5" endX="4" endY="-7.5" />
    <Segment startX="4" startY="-7.5" endX="4" endY="-4.5" />
    <Segment startX="4" startY="-4.5" endX="2" endY="-3.5" />
    <Segment startX="2" startY="-8.5" endX="2" endY="-5.5" />
    <Segment startX="2" startY="-5.5" endX="0" endY="-4.5" />
    <Segment startX="2" startY="-5.5" endX="4" endY="-4.5" />
    <Segment startX="-6" startY="-3.5" endX="-6" endY="-0.5" />
    <Segment startX="-6" startY="-0.5" endX="-4" endY="0.5" />
    <Segment startX="-4" startY="0.5" endX="-4" endY="3.5" />
    <Segment startX="-4" startY="3.5" endX="-2" endY="4.5" />
    <Segment startX="2" startY="-3.5" endX="2" endY="-0.5" />
    <Segment startX="2" startY="-0.5" endX="0" endY="0.5" />
    <Segment startX="0" startY="0.5" endX="0" endY="3.5" />
    <Segment startX="0" startY="3.5" endX="-2" endY="4.5" />
    <Segment startX="0" startY="-4.5" endX="0" endY="-1.5" />
    <Segment startX="0" startY="-1.5" endX="-2" endY="-0.5" />
    <Segment startX="-2" startY="-0.5" endX="-2" endY="2.5" />
    <Segment startX="-2" startY="2.5" endX="-4" endY="3.5" />
    <Segment startX="0" startY="-1.5" endX="2" endY="-0.5" />
    <Segment startX="-2" startY="-0.5" endX="0" endY="0.5" />
    <Segment startX="-2" startY="2.5" endX="0" endY="3.5" />
    <Segment startX="-4" startY="-4.5" endX="-4" endY="-1.5" />
    <Segment startX="-4" startY="-1.5" endX="-6" endY="-0.5" />
    <Segment startX="-4" startY="-1.5" endX="-2" endY="-0.5" />
    <Segment startX="-2" startY="-0.5" endX="-4" endY="0.5" />
    <Segment startX="-2" startY="-3.5" endX="-2" endY="-0.5" />
    <Segment startX="6" startY="-8.5" endX="8" endY="-7.5" />
    <Segment startX="8" startY="-7.5" endX="8" endY="-4.5" />
    <Segment startX="8" startY="-4.5" endX="6" endY="-3.5" />
    <Segment startX="6" startY="-3.5" endX="6" endY="-0.5" />
    <Segment startX="6" startY="-0.5" endX="4" endY="0.5" />
    <Segment startX="4" startY="0.5" endX="4" endY="3.5" />
    <Segment startX="4" startY="3.5" endX="2" endY="4.5" />
    <Segment startX="6" startY="-8.5" endX="6" endY="-5.5" />
    <Segment startX="6" startY="-5.5" endX="4" endY="-4.5" />
    <Segment startX="4" startY="-4.5" endX="4" endY="-1.5" />
    <Segment startX="4" startY="-1.5" endX="2" endY="-0.5" />
    <Segment startX="2" startY="-0.5" endX="2" endY="2.5" />
    <Segment startX="2" startY="2.5" endX="0" endY="3.5" />
    <Segment startX="6" startY="-8.5" endX="4" endY="-7.5" />
    <Segment startX="6" startY="-5.5" endX="8" endY="-4.5" />
    <Segment startX="4" startY="-4.5" endX="6" endY="-3.5" />
    <Segment startX="4" startY="-1.5" endX="6" endY="-0.5" />
    <Segment startX="2" startY="-0.5" endX="4" endY="0.5" />
    <Segment startX="2" startY="2.5" endX="4" endY="3.5" />
    <Segment startX="0" startY="3.5" endX="2" endY="4.5" />
    <Segment startX="-2" startY="4.5" endX="-2" endY="7.5" />
    <Segment startX="-2" startY="7.5" endX="0" endY="8.5" />
    <Segment startX="0" startY="6.5" endX="-2" endY="7.5" />
    <Segment startX="0" startY="3.5" endX="0" endY="6.5" />
    <Segment startX="0" startY="6.5" endX="2" endY="7.5" />
    <Segment startX="2" startY="7.5" endX="0" endY="8.5" />
    <Segment startX="2" startY="4.5" endX="2" endY="7.5" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Snipers</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Diamond.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Blue_Gradient.png" backgroundTileRate="64" >
  <difficulty>easy</difficulty>
  <description>It has four points.</description>
  <randomWaveCount>0</randomWaveCount>
  <Waves>
    <Wave type="Assassin" budget="64" time="1.1" />
    <Wave type="Assassin" budget="87" time="2.2" />
    <Wave type="Scrambled" budget="119" time="3.30000019" />
    <Wave type="Scrambled" budget="161" time="4.4" />
    <Wave type="Assassin" budget="213" time="5.5" />
    <Wave type="Scrambled" budget="274" time="6.60000038" />
    <Wave type="Scrambled" budget="345" time="7.70000029" />
    <Wave type="Assassin" budget="426" time="8.8" />
    <Wave type="Scrambled" budget="516" time="9.900001" />
    <Wave type="Assassin" budget="617" time="11" />
    <Wave type="Scrambled" budget="726" time="12.1" />
    <Wave type="Scrambled" budget="846" time="13.2000008" />
    <Wave type="Assassin" budget="975" time="14.3" />
    <Wave type="Assassin" budget="1114" time="15.4000006" />
    <Wave type="Scrambled" budget="1263" time="16.5" />
    <Wave type="Scrambled" budget="1422" time="17.6" />
    <Wave type="Assassin" budget="1590" time="18.7" />
    <Wave type="Assassin" budget="1768" time="19.8000011" />
    <Wave type="Scrambled" budget="1955" time="20" />
    <Wave type="Assassin" budget="2153" time="20" />
  </Waves>
  <Spawners>
    <Spawner spawnX="0.5" spawnY="-4.5" />
  </Spawners>
  <PathSegments>
    <Segment startX="0.5" startY="-4.5" endX="0.5" endY="-3.5" />
    <Segment startX="0.5" startY="-3.5" endX="1.5" endY="-3.5" />
    <Segment startX="1.5" startY="-3.5" endX="1.5" endY="-2.5" />
    <Segment startX="1.5" startY="-2.5" endX="2.5" endY="-2.5" />
    <Segment startX="2.5" startY="-2.5" endX="2.5" endY="-1.5" />
    <Segment startX="2.5" startY="-1.5" endX="3.5" endY="-1.5" />
    <Segment startX="3.5" startY="-1.5" endX="3.5" endY="-0.5" />
    <Segment startX="3.5" startY="-0.5" endX="4.5" endY="-0.5" />
    <Segment startX="4.5" startY="-0.5" endX="4.5" endY="0.5" />
    <Segment startX="4.5" startY="0.5" endX="3.5" endY="0.5" />
    <Segment startX="3.5" startY="0.5" endX="3.5" endY="1.5" />
    <Segment startX="3.5" startY="1.5" endX="2.5" endY="1.5" />
    <Segment startX="2.5" startY="1.5" endX="2.5" endY="2.5" />
    <Segment startX="2.5" startY="2.5" endX="1.5" endY="2.5" />
    <Segment startX="1.5" startY="2.5" endX="1.5" endY="3.5" />
    <Segment startX="1.5" startY="3.5" endX="0.5" endY="3.5" />
    <Segment startX="0.5" startY="3.5" endX="0.5" endY="4.5" />
    <Segment startX="0.5" startY="4.5" endX="-0.5" endY="4.5" />
    <Segment startX="-0.5" startY="4.5" endX="-0.5" endY="3.5" />
    <Segment startX="-0.5" startY="3.5" endX="-1.5" endY="3.5" />
    <Segment startX="-1.5" startY="3.5" endX="-1.5" endY="2.5" />
    <Segment startX="-1.5" startY="2.5" endX="-2.5" endY="2.5" />
    <Segment startX="-2.5" startY="2.5" endX="-2.5" endY="1.5" />
    <Segment startX="-2.5" startY="1.5" endX="-3.5" endY="1.5" />
    <Segment startX="-3.5" startY="1.5" endX="-3.5" endY="0.5" />
    <Segment startX="-3.5" startY="0.5" endX="-4.5" endY="0.5" />
    <Segment startX="-4.5" startY="0.5" endX="-4.5" endY="-0.5" />
    <Segment startX="-4.5" startY="-0.5" endX="-3.5" endY="-0.5" />
    <Segment startX="-3.5" startY="-0.5" endX="-3.5" endY="-1.5" />
    <Segment startX="-3.5" startY="-1.5" endX="-2.5" endY="-1.5" />
    <Segment startX="-2.5" startY="-1.5" endX="-2.5" endY="-2.5" />
    <Segment startX="-2.5" startY="-2.5" endX="-1.5" endY="-2.5" />
    <Segment startX="-1.5" startY="-2.5" endX="-1.5" endY="-3.5" />
    <Segment startX="-1.5" startY="-3.5" endX="-0.5" endY="-3.5" />
    <Segment startX="-0.5" startY="-3.5" endX="-0.5" endY="-4.5" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <levelDeck name="Diamond Deck">
    <Cards>
      <Card name="Enrage" count="2" />
      <Card name="Explosive Tower" count="3" />
      <Card name="Infrastructure Funding" count="3" />
      <Card name="Light Shield" count="3" />
      <Card name="Quad-Barrel Upgrade" count="4" />
      <Card name="Range Upgrade" count="5" />
      <Card name="Resonant Tower (A)" count="10" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/symmetry.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>medium</difficulty>  
  <description>Two symmetrical spirals.  The default level deck here contains no towers.</description>
  <randomWaveCount>14</randomWaveCount>
  <Waves>
    <Wave type="Standard" budget="116" time="1.1" />
  </Waves>
  <Spawners>
    <Spawner spawnX="0" spawnY="0" />
    <Spawner spawnX="0" spawnY="1" />
  </Spawners>
  <PathSegments>
    <Segment startX="0" startY="0" endX="0" endY="-1" />
    <Segment startX="0" startY="-1" endX="2" endY="-1" />
    <Segment startX="2" startY="-1" endX="2" endY="3" />
    <Segment startX="2" startY="3" endX="-8" endY="3" />
    <Segment startX="-8" startY="3" endX="-8" endY="-2" />
    <Segment startX="-8" startY="-2" endX="-4" endY="-2" />
    <Segment startX="-4" startY="-2" endX="-4" endY="2" />
    <Segment startX="-4" startY="2" endX="-7" endY="2" />
    <Segment startX="-7" startY="2" endX="-7" endY="-1" />
    <Segment startX="-7" startY="-1" endX="-5" endY="-1" />
    <Segment startX="-5" startY="-1" endX="-5" endY="1" />
    <Segment startX="-5" startY="1" endX="-6" endY="1" />
    <Segment startX="0" startY="1" endX="0" endY="2" />
    <Segment startX="0" startY="2" endX="-2" endY="2" />
    <Segment startX="-2" startY="2" endX="-2" endY="-2" />
    <Segment startX="-2" startY="-2" endX="8" endY="-2" />
    <Segment startX="8" startY="-2" endX="8" endY="3" />
    <Segment startX="8" startY="3" endX="4" endY="3" />
    <Segment startX="4" startY="3" endX="4" endY="-1" />
    <Segment startX="4" startY="-1" endX="7" endY="-1" />
    <Segment startX="7" startY="-1" endX="7" endY="2" />
    <Segment startX="7" startY="2" endX="5" endY="2" />
    <Segment startX="5" startY="2" endX="5" endY="0" />
    <Segment startX="5" startY="0" endX="6" endY="0" />
  </PathSegments>
  <Towers>
    <Tower name="Heavy Tower" x="-6.5" y="0.5" />
    <Tower name="Heavy Tower" x="-5.5" y="0.5" />
    <Tower name="Heavy Tower" x="-6.5" y="-0.5" />
    <Tower name="Heavy Tower" x="-5.5" y="-0.5" />
    <Tower name="Fast Tower" x="-6.5" y="0" />
    <Tower name="Fast Tower" x="-6" y="0.5" />
    <Tower name="Fast Tower" x="-6" y="-0.5" />
    <Tower name="Fast Tower" x="-5.5" y="0" />
    <Tower name="Basic Tower" x="-6" y="0" />
    <Tower name="Heavy Tower" x="6.5" y="1.5" />
    <Tower name="Heavy Tower" x="5.5" y="1.5" />
    <Tower name="Heavy Tower" x="6.5" y="0.5" />
    <Tower name="Heavy Tower" x="5.5" y="0.5" />
    <Tower name="Fast Tower" x="6.5" y="1" />
    <Tower name="Fast Tower" x="6" y="1.5" />
    <Tower name="Fast Tower" x="6" y="0.5" />
    <Tower name="Fast Tower" x="5.5" y="1" />
    <Tower name="Basic Tower" x="6" y="1" />
  </Towers>
  <shuffleDeck>true</shuffleDeck>
  <levelDeck name="Level Deck">
    <Cards>
      <Card name="Enrage" count="4" />
      <Card name="Fast Upgrade" count="10" />
      <Card name="Heavy Upgrade" count="10" />
      <Card name="Recycle" count="3" />
      <Card name="Shield" count="3" />
    </Cards>
  </levelDeck>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Parallel tasks.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>hard</difficulty>
  <description>A challenging map with two wide but short paths to defend</description>
  <randomWaveCount>15</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="-5" spawnY="1" />
    <Spawner spawnX="-5" spawnY="1.5" />
    <Spawner spawnX="-5" spawnY="2" />
    <Spawner spawnX="5" spawnY="-1" />
    <Spawner spawnX="5" spawnY="-1.5" />
    <Spawner spawnX="5" spawnY="-2" />
  </Spawners>
  <PathSegments>
    <Segment startX="-5" startY="1" endX="5" endY="1" />
    <Segment startX="-5" startY="1.5" endX="5" endY="1.5" />
    <Segment startX="-5" startY="2" endX="5" endY="2" />
    <Segment startX="5" startY="-1" endX="-5" endY="-1" />
    <Segment startX="5" startY="-1.5" endX="-5" endY="-1.5" />
    <Segment startX="5" startY="-2" endX="-5" endY="-2" />
  </PathSegments>
  <Towers>
    <Tower name="Basic Tower" x="-4" y="0" />
    <Tower name="Basic Tower" x="-2" y="0" />
    <Tower name="Basic Tower" x="0" y="0" />
    <Tower name="Basic Tower" x="2" y="0" />
    <Tower name="Basic Tower" x="4" y="0" />
  </Towers>
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Spitfire</premadeDeckName>
</Level>

=== mctribble/Card-Defense/Assets/StreamingAssets/XML/Levels/Robert.xml
<?xml version="1.0" encoding="utf-8"?>
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Level.xsd" background="Black.png">
  <difficulty>medium</difficulty>
  <description>Fine, YOU try naming this thing.</description>
  <randomWaveCount>30</randomWaveCount>
  <Waves />
  <Spawners>
    <Spawner spawnX="1" spawnY="-2" />
    <Spawner spawnX="3" spawnY="-6" />
    <Spawner spawnX="6" spawnY="-2" />
  </Spawners>
  <PathSegments>
    <Segment startX="1" startY="-2" endX="-3" endY="-2" />
    <Segment startX="-3" startY="-2" endX="-3" endY="3" />
    <Segment startX="-3" startY="3" endX="-7" endY="3" />
    <Segment startX="-7" startY="3" endX="-7" endY="-6" />
    <Segment startX="-7" startY="-6" endX="2" endY="-6" />
    <Segment startX="2" startY="-6" endX="2" endY="-2" />
    <Segment startX="3" startY="-6" endX="3" endY="-1" />
    <Segment startX="3" startY="-1" endX="-2" endY="-1" />
    <Segment startX="-2" startY="-1" endX="-2" endY="3" />
    <Segment startX="-2" startY="3" endX="9" endY="3" />
    <Segment startX="9" startY="3" endX="9" endY="-1" />
    <Segment startX="9" startY="-1" endX="4" endY="-1" />
    <Segment startX="4" startY="-1" endX="4" endY="-6" />
    <Segment startX="6" startY="-2" endX="10" endY="-2" />
    <Segment startX="10" startY="-2" endX="10" endY="3" />
    <Segment startX="10" startY="3" endX="14" endY="3" />
    <Segment startX="14" startY="3" endX="14" endY="-6" />
    <Segment startX="14" startY="-6" endX="5" endY="-6" />
    <Segment startX="5" startY="-6" endX="5" endY="-2" />
  </PathSegments>
  <Towers />
  <shuffleDeck>true</shuffleDeck>
  <premadeDeckName>Challenger</premadeDeckName>
</Level>
